### ISSUE TITLE
build.sh脚本中一些疑惑

### ISSUE THREAD

**Issue by HuberyYan** [lixiangyun/grpc-c#2]
protoc -I $1 --grpc-c_out=$1 --plugin=protoc-gen-grpc-c=/usr/local/bin/protoc-gen-grpc-c $1/$2
上面这行命令中，--grpc-c_out这个命名有什么特殊意义吗？我看本身的命令里面，并没有这个指令；
而且这个命名和protoc-gen-grpc-c有什么关系，我试图修改grpc-c_out为grpc_out，结果报错：
protoc-gen-grpc: program not found or is not executable
--grpc_out: protoc-gen-grpc: Plugin failed with status code 1

**Comment by lixiangyun** [comment]
用于插件的调用，{grpc-c}_out 就会找工具 protoc-gen-{grpc-c}
