### ISSUE TITLE
客户端流式调用的replay

### ISSUE THREAD

**Issue by HuberyYan** [lixiangyun/grpc-c#3]
之前的问题都解决了！
即将成功的最后一步，出现了新的问题，步骤如下：
①客户端发送获取文件请求；
②获取响应，并释放响应结构体；
③对得到的响应流进行处理，比如文件写出；
④根据写出的文件内容，再次发送请求；
但是程序运行完第二步就卡住不再往下走了，找不到原因。部分代码如下：
            ret = grpc_c_write(context, &h, 0, -1);
            if (ret)
            {
                printf("stream write failed!(one) %d\n", ret);
            }
            // ②从服务端获取响应的子文件
            for (i = 0;; i++)
            {
                printf("get reply! %d\n", i);
                foo__HelloReply *r;
                ret = grpc_c_read(context, (void **)&r, 0, -1);
                if (ret)
                    break;
                // 获取文件地址
                char *name = r->name;
                printf("get every child file! %s\n", name);
                // ProtobufCBinaryData *pcb = &(r->message);
                // ③不存在的创建
                if (access(name, 0) != 0)
                {
                    printf("the file is not exist,it will be creat! %s\n", name);
                    mkdirs(name);
                }
                foo__hello_reply_free(r);
            }
            //获取每个子文件地址和大小
            readFileList(filePath);
            int size_t;
            for (i = 0; i < n; i++)
            {
                // 多次请求
                long long tempLen = getFileLen(fileNameList[i]);
                if (tempLen == -1)
                {
                    return;
                }
                fileLen = tempLen;
                // 给请求参数赋值
                sprintf(str, "%s,%lld", fileNameList[i], fileLen); // 格式为: "filePath,fileLen"
                h.name = str;
                ret = grpc_c_write(context, &h, 0, -1);
                if (ret)
                {
                    printf("stream write failed!(two) %d\n", ret);
                }
            }
代码如上，响应只有9个元素，全部获取到以后，第十次走到read那里就卡住了，也不结束，需要手动结束，结果如下：
[root@hosts examples]# ./bin/foo_bin /home/yh/y1yy
args : /home/yh/y1yy
It is a folder,the file path is : /home/yh/y1yy
get reply! 0
get every child file! /home/yh/y1yy/y12
get reply! 1
get every child file! /home/yh/y1yy/y11
get reply! 2
get every child file! /home/yh/y1yy/y2yy/y23
get reply! 3
get every child file! /home/yh/y1yy/y2yy/y3yy/y32
get reply! 4
get every child file! /home/yh/y1yy/y2yy/y3yy/y31
get reply! 5
get every child file! /home/yh/y1yy/y2yy/y3yy/y33
get reply! 6
get every child file! /home/yh/y1yy/y2yy/y21
get reply! 7
get every child file! /home/yh/y1yy/y2yy/y22
get reply! 8
get every child file! /home/yh/y1yy/y13
get reply! 9
^C
[root@hosts examples]#

**Comment by lixiangyun** [comment]
请附上你的proto文件和代码吧

**Comment by HuberyYan** [comment]
> 请附上你的proto文件和代码吧

之前的问题都解决了！
即将成功的最后一步，出现了新的问题，步骤如下：
①客户端发送获取文件请求；
②获取响应，并释放响应结构体；
③对得到的响应流进行处理，比如文件写出；
④根据写出的文件内容，再次发送请求；
但是程序运行完第二步就卡住不再往下走了，找不到原因。部分代码如下：
// ②从服务端获取响应的子文件
for (i = 0;; i++)
{
printf("get reply! %d\n", i);
foo__HelloReply *r;
ret = grpc_c_read(context, (void **)&r, 0, -1);
if (ret)
break;
// 获取文件地址
char *name = r->name;
printf("get every child file! %s\n", name);
// ProtobufCBinaryData *pcb = &(r->message);
// ③不存在的创建
if (access(name, 0) != 0)
{
printf("the file is not exist,it will be creat! %s\n", name);
mkdirs(name);
}
foo__hello_reply_free(r);
}
//获取每个子文件地址和大小
readFileList(filePath);
int size_t;
for (i = 0; i < n; i++)
{
// 多次请求
long long tempLen = getFileLen(fileNameList[i]);
if (tempLen == -1)
{
return;
}
fileLen = tempLen;
// 给请求参数赋值
sprintf(str, "%s,%lld", fileNameList[i], fileLen); // 格式为: "filePath,fileLen"
h.name = str;
ret = grpc_c_write(context, &h, 0, -1);
if (ret)
{
printf("stream write failed!(two) %d\n", ret);
}
}
代码如上，第一个for循环走完以后，程序往下就不再运行了，没有报错，也不结束，需要手动结束，结果如下：
[root@hosts examples]# ./bin/foo_bin /home/yh/y1yy
args : /home/yh/y1yy
It is a folder,the file path is : /home/yh/y1yy
get reply! 0
get every child file! /home/yh/y1yy/y12
get reply! 1
get every child file! /home/yh/y1yy/y11
get reply! 2
get every child file! /home/yh/y1yy/y2yy/y23
get reply! 3
get every child file! /home/yh/y1yy/y2yy/y3yy/y32
get reply! 4
get every child file! /home/yh/y1yy/y2yy/y3yy/y31
get reply! 5
get every child file! /home/yh/y1yy/y2yy/y3yy/y33
get reply! 6
get every child file! /home/yh/y1yy/y2yy/y21
get reply! 7
get every child file! /home/yh/y1yy/y2yy/y22
get reply! 8
get every child file! /home/yh/y1yy/y13
get reply! 9
^C
[root@hosts examples]#

**Comment by lixiangyun** [comment]
流模式下，如果客户端需要结束写操作，那么需要调用 grpc_c_write_done。并且最终调用 grpc_c_finish 结束流模式。

**Comment by HuberyYan** [comment]
> 流模式下，如果客户端需要结束写操作，那么需要调用 grpc_c_write_done。并且最终调用 grpc_c_finish 结束流模式。
> 流模式下，服务端在结束之前，不需要 grpc_c_write_done ，但是必须调用 grpc_c_finish 。

之前我写操作完成后，调用grpc_c_write_done，响应的循环正常执行，但是接下来发送新的请求时，提示写入失败，是需要重新创建context对象吗？
刚才按照您的提示，我试着在写完后加入grpc_c_finish(context, GRPC_C_STATE_NEW, 0)无效，结果仍然是卡在第九个read那一步

**Comment by lixiangyun** [comment]
grpc_c_write_done 之后就不能再 grpc_c_write了，这个需要看你在什么时候完全结束流模式。如果不结束，可以一直写操作。

**Comment by HuberyYan** [comment]
我需要第一次写操作，获取响应后，再把响应得到的数据，再进行写操作发送给客户端，中间不能done掉，所以这就出现了一开始获取响应时，卡住了。。。

**Comment by lixiangyun** [comment]
是这样的，客户端读写都是同步操作，也是就是必须等服务端再次write，客户端read才会成功。如果你服务端write 10次，那么客户端read成功十次，第十一次必然阻塞。你可以在客户端开两个线程，读写分离操作。在结束之前，如果服务端不在write，那么客户端read始终阻塞。直到客户端write done以及finish结束本次流模式。
